/*
 Generated by typeshare 1.13.4
*/

/**
 * One `backlog[]` node that has crossed the backlog staleness threshold — used for both the
 * `aging_backlog` lane (non-capture nodes) and the `orphaned_captures` lane (`origin.type ==
 * "capture"` nodes, never both).
 * 
 * Wire format:
 * ```json
 * { "repo": "bastion", "slug": "serve-attention-endpoint", "title": "Attention projection",
 * "kind": "feature", "status": "ready", "notes": null,
 * "created": "2026-07-10", "reviewed": null,
 * "age_days": 14, "threshold_days": 7 }
 * ```
 */
export interface AttentionBacklogDto {
	/** Owning repo slug. */
	repo: string;
	/** Stable item slug. */
	slug: string;
	/** Human-readable title. */
	title: string;
	/** Backlog kind (serde-renamed from `type` on the domain type). */
	kind: string;
	/** Lifecycle status (`"idea"` / `"ready"`, the only statuses that can age). */
	status: string;
	/**
	 * Notes; for `orphaned_captures` this is `origin.notes` falling back to the node's own
	 * `notes`.
	 */
	notes?: string;
	/** Creation date (`YYYY-MM-DD`), when recorded. */
	created?: string;
	/** Last-reviewed date (`YYYY-MM-DD`), when recorded. */
	reviewed?: string;
	/** Days past the anchor date (`max(created, reviewed)`), as of `as_of`. */
	age_days: number;
	/** The `backlog_days` threshold this item tripped. */
	threshold_days: number;
}

/**
 * Projects `mev::CarryoverRanking` verbatim (repo/slug/kind/lane/priority/
 * effective_priority/unmet_blocks/finding_id/clears_when_satisfied) alongside the
 * original entry's display fields (text/clears_when/created/reviewed/threshold_days).
 * Every `Option` serializes as an absent key when `None` — never `null` — matching
 * this repo's established absent-is-never-neutral convention (BA.ticket
 * .carryover-triage-dto task 2).
 */
export interface AttentionCarryoverDto {
	/** Owning repo slug. */
	repo: string;
	/** Stable item slug. */
	slug: string;
	/** Carryover kind (`"env"`, `"deferred"`, `"known_issue"`, `"constraint"`, or other). */
	kind: string;
	/** The carryover text itself, untruncated. */
	text: string;
	/** What clears this item, when recorded. */
	clears_when?: string;
	/** Creation date (`YYYY-MM-DD`), when recorded. */
	created?: string;
	/** Last-reviewed date (`YYYY-MM-DD`), when recorded. */
	reviewed?: string;
	/**
	 * Days past the anchor date (`max(created, reviewed)`), as of `as_of`. `None`
	 * when the entry is currently snoozed or has no parseable anchor date — such
	 * entries still reach the board (contract §2; they no longer have to be
	 * stale-with-an-age to be included).
	 */
	age_days?: number;
	/** The per-`kind` threshold this item tripped. */
	threshold_days: number;
	/**
	 * The triage lane `mev::rank_carryover` assigned (`blocking|hot|aging|standing`).
	 * Never re-derived here — see contract §6 rule 1.
	 * 
	 * `TriageLane` is defined in the `mev` crate, outside typeshare's
	 * `src/serve` scan root, so it cannot resolve as a cross-crate type
	 * reference. `serialized_as = "string"` emits the wire shape (one of the
	 * four kebab-case lane names) directly instead of an unresolved
	 * `TriageLane` reference in the generated file.
	 */
	lane: string;
	/** Authored `priority`, verbatim from `mev::CarryoverRanking`. */
	priority?: number;
	/**
	 * Effective priority (reverse-topo min-propagation over `blocks[]` edges),
	 * verbatim from `mev::CarryoverRanking`.
	 */
	effective_priority?: number;
	/**
	 * Unmet `blocks[]` edges. Non-empty iff this entry is in the BLOCKING lane.
	 * There is deliberately no `blocking: bool` field (contract §6 rule 2) —
	 * consumers derive it from `!unmet_blocks.is_empty()`.
	 */
	unmet_blocks?: string[];
	/** Free-form cross-repo finding identity, verbatim from `mev::CarryoverRanking`. */
	finding_id?: string;
	/**
	 * Whether every reference extracted from `clears_when` is currently satisfied
	 * (`mev::CarryoverLane::Cleared`), verbatim from `mev::CarryoverRanking`.
	 */
	clears_when_satisfied: boolean;
}

/**
 * `scope` query param for `GET /api/board`.
 * 
 * Deserializes from the lowercase wire values (`"hq"`, `"tier"`, `"project"`,
 * `"business"`, `"epic"`); missing/absent `scope` defaults to
 * [`BoardScope::Hq`]. An unknown scope string fails to deserialize (surfaced
 * as a 400 via the existing malformed-request `ErrorPayload` path).
 */
export enum BoardScope {
	/** Whole-brain aggregate (`mev::brain::state::TierScope::All`). */
	Hq = "hq",
	/** Single tier's aggregate board (`TierScope::Tier(<tier>)`, default `"core"`). */
	Tier = "tier",
	/**
	 * Single tier resolved per-project (client renders each project's board
	 * from `repos[]`); same underlying `TierScope::Tier(<tier>)`.
	 */
	Project = "project",
	/** Shortcut for `tier=business` (`TierScope::Tier("business")`). */
	Business = "business",
	/**
	 * Cross-repo initiative projection — every block tagged with the
	 * `&epic=<slug>` query param's epic, across every repo (`TierScope::All`).
	 * `epic` is **required** for this scope; absent or unknown → 404/`C005`.
	 */
	Epic = "epic",
}

/** The three Attention board lanes. */
export interface AttentionLanesDto {
	/** `carryover[]` entries past their per-`kind` threshold, oldest-first. */
	stale_carryover?: AttentionCarryoverDto[];
	/** Non-capture `backlog[]` nodes past `backlog_days`, oldest-first. */
	aging_backlog?: AttentionBacklogDto[];
	/** `backlog[]` nodes with `origin.type == "capture"` past `backlog_days`, oldest-first. */
	orphaned_captures?: AttentionBacklogDto[];
}

/**
 * The resolved `brain.toml` `[attention]` thresholds, mirroring
 * `mev::brain::config::AttentionThresholds`.
 */
export interface AttentionThresholdsDto {
	/** Threshold (days) for `kind == "env"` carryover. */
	env_days: number;
	/** Threshold (days) for `kind == "deferred"` carryover. */
	deferred_days: number;
	/** Threshold (days) for `kind == "known_issue"` carryover. */
	known_issue_days: number;
	/** Threshold (days) for `kind == "constraint"` carryover. */
	constraint_days: number;
	/** Threshold (days) for aging/orphaned `backlog[]` nodes. */
	backlog_days: number;
}

/** JSON response for `GET /api/attention?scope=hq|tier|project|business[&tier=<name>]`. */
export interface AttentionDto {
	/**
	 * The resolved scope this response was projected under. Reuses [`BoardScope`] — the
	 * `/api/attention` query semantics are identical to `/api/board`.
	 */
	scope?: BoardScope;
	/** The resolved tier name, when `scope` is tier-scoped (`None` for `hq`). */
	tier?: string;
	/** `YYYY-MM-DD` the ages were computed against. */
	as_of: string;
	/** The three Attention lanes. */
	lanes: AttentionLanesDto;
	/** The resolved thresholds used to compute every `age_days` / `threshold_days` pair above. */
	thresholds: AttentionThresholdsDto;
}

/**
 * Mirrors `mev::brain::block_graph::BlockLane`'s six variants. Serialises
 * `snake_case` to match upstream (`"now"`, `"next"`, `"blocked"`, `"deferred"`,
 * `"closed"`, `"other"`).
 */
export enum BlockLaneDto {
	/** Authored `status == "in_progress"`. */
	Now = "now",
	/** Ready — open, no external deps, all block deps closed. */
	Next = "next",
	/** Open with at least one unmet dependency. */
	Blocked = "blocked",
	/** Authored `status == "deferred"`. */
	Deferred = "deferred",
	/** Authored `status == "closed"`. */
	Closed = "closed",
	/** An authored status that matches none of the above. */
	Other = "other",
}

/**
 * Mirrors `mev::brain::block_graph::BlockGraphNode` field-for-field.
 * 
 * Wire format:
 * ```json
 * {
 * "key": "bastion:BA.17.A", "repo": "bastion", "id": "BA.17.A",
 * "title": "GET /api/blocks/graph endpoint", "status": "in_progress",
 * "lane": "now", "track": "Phase 17", "wave": 1, "priority": 1,
 * "effective_priority": 1, "due": null, "epics": ["bastion-surfaces"],
 * "layer": 0, "topo_index": 4, "ready": true, "in_cycle": false,
 * "in_scope": true, "external_deps": [], "unmet_count": 0, "dependent_count": 0
 * }
 * ```
 */
export interface BlockGraphNodeDto {
	/** Canonical `"repo:id"` key. */
	key: string;
	/** Owning repo slug. */
	repo: string;
	/** Canonical block ID. */
	id: string;
	/** Brief human description. */
	title: string;
	/** Authored lifecycle status (`open`/`in_progress`/`deferred`/`closed`), if any. */
	status?: string;
	/** Derived attention lane. */
	lane: BlockLaneDto;
	/** Title of the containing `tracks[]` phase/wave, if resolvable. */
	track?: string;
	/** Authored execution-order rank. */
	wave?: number;
	/** Authored own priority. */
	priority?: number;
	/** Effective priority — absent when it never lands in the real `0..=3` range. */
	effective_priority?: number;
	/** Authored due date/timing string. */
	due?: string;
	/** Cross-repo epic membership. */
	epics?: string[];
	/** Longest path over resolved `depends_on` edges (`0` = no resolved prerequisites). */
	layer: number;
	/** Position in the full-corpus topological order. */
	topo_index: number;
	/** Membership in the ready-order set. */
	ready: boolean;
	/** Whether this node participates in a `depends_on` cycle. */
	in_cycle: boolean;
	/** Whether this node survives the scope pipeline's tier/repo/epic/closed stages. */
	in_scope: boolean;
	/** `what` strings from this block's `{type:"external"}` `depends_on` entries. */
	external_deps?: string[];
	/** Count of unmet dependencies for a `Blocked` node — `0` for every other lane. */
	unmet_count: number;
	/** Corpus-wide count of in-corpus blocks whose `BlockedBy` edges point at this node. */
	dependent_count: number;
}

/**
 * Mirrors `okf_core::state::StateEdgeKind`'s two variants. Serialises
 * `snake_case` to match upstream (`"blocked_by"`, `"cross_repo"`). Declared
 * locally rather than reusing `okf_core::StateEdgeKind` — see the module note
 * above.
 */
export enum BlockEdgeKindDto {
	/** A `blocked_by` dependency (a block is waiting on another block). */
	BlockedBy = "blocked_by",
	/** An explicit cross-repo dependency declared in a brain file's `cross_repo[]`. */
	CrossRepo = "cross_repo",
}

/**
 * Mirrors `mev::brain::block_graph::BlockGraphEdge` field-for-field.
 * 
 * Wire format:
 * ```json
 * { "from": "bastion:BA.17.A", "to_ref": "mev:MV.10.B", "kind": "blocked_by",
 * "target_node_id": "mev:MV.10.B", "blocking": false }
 * ```
 */
export interface BlockGraphEdgeDto {
	/** `"repo:id"` key of the source (dependent) block. */
	from: string;
	/** Raw, as-authored `"repo:id"` reference. */
	to_ref: string;
	/** Edge discriminant. */
	kind: BlockEdgeKindDto;
	/** `Some(to_ref)` when it resolves to a node in this export; `None` when dangling. */
	target_node_id?: string;
	/** `false` when either endpoint is `closed`. */
	blocking: boolean;
}

/**
 * JSON response for `GET /api/blocks/graph?scope=...&tier=...&epic=...&repo=...
 * &include_closed=...&include_boundary=...&max_nodes=...`.
 * 
 * A mechanical projection of `mev::brain::block_graph::BlockGraphExport` plus the
 * response-level `scope` echo (reusing [`BoardScope`]) and `stale` flag, matching
 * `BoardDto`'s convention.
 */
export interface BlockGraphDto {
	/** Schema version — currently `"1"`. */
	version: string;
	/** Display path of the brain root used for the build. */
	root: string;
	/** The resolved scope this response was projected under. */
	scope?: BoardScope;
	/** The resolved tier name, when `scope` is tier-scoped (`None` for `hq`). */
	tier?: string;
	/** The resolved `&epic=` slug, when `scope=epic`. */
	epic?: string;
	/** The resolved `&repo=` restriction, when present. */
	repo?: string;
	/** Whether `Closed`-lane nodes were retained. */
	include_closed: boolean;
	/** Whether direct neighbours of the in-scope set were re-added as boundary nodes. */
	include_boundary: boolean;
	/** Nodes, emitted in `topo_index` order. */
	nodes?: BlockGraphNodeDto[];
	/** Edges — one per surviving scoped edge. */
	edges?: BlockGraphEdgeDto[];
	/** Cycles found over the full corpus (never the scoped subgraph). */
	cycles?: string[][];
	/** Node count before any `max_nodes` truncation. */
	total_nodes: number;
	/** Whether `max_nodes` truncated the node list. */
	truncated: boolean;
	/**
	 * Freshness flag: `true` when any in-scope repo's `status.md` cache lags its
	 * `state.json` (same posture as `BoardDto::stale`).
	 */
	stale: boolean;
}

/**
 * One lane entry (a single now/next/blocked/finished block) in a board response.
 * 
 * Wire format:
 * `{ "id": "BA.11.K", "title": "Cross-brain board read endpoint", "repo": "bastion", "status": "in_progress", "blocked_by": [], "epics": ["bastion-surfaces"], "wave": 3, "priority": 1, "due": "2026-07-15", "track": "Phase 11" }`
 */
export interface BoardBlockDto {
	/** Canonical block ID (e.g. `BA.11.K`). */
	id: string;
	/** Brief human description, looked up from the owning repo's `tracks[].blocks[]`. */
	title: string;
	/** Owning repo slug. */
	repo: string;
	/** Lifecycle status, when known (`"open"`/`"in_progress"`/`"closed"`). */
	status?: string;
	/** What this block is waiting on (populated for `blocked` lane entries). */
	blocked_by?: BlockedBy[];
	/**
	 * Cross-repo epic membership — slugs into the HQ `epics[]` registry.
	 * 
	 * Joined back from the owning repo's `tracks[].blocks[]`: the rollup
	 * entries `derive_rollup` produces hard-code this empty (see
	 * `../mev/src/brain/state.rs` ~2212–2257). Unlike `okf_core`, this DTO does
	 * **not** carry `skip_serializing_if` — the wire always shows `[]` so TS
	 * clients get a stable array rather than an absent key.
	 */
	epics?: string[];
	/**
	 * Execution-order rank for "what's next", from the authoring `TrackBlock`.
	 * 
	 * Typed `i64` to mirror `okf_core::TrackBlock.wave` exactly (the master plan
	 * wrote `u32`; casting would mangle out-of-range authored values).
	 */
	wave?: number;
	/** Execution priority (e.g. 1, 2, 3), from the authoring `TrackBlock`. */
	priority?: number;
	/**
	 * Target due date or timing string (e.g. `"2026-07-15"`), from the
	 * authoring `TrackBlock`.
	 */
	due?: string;
	/** Title of the enclosing `tracks[]` phase/wave entry (`okf_core::Track.title`). */
	track?: string;
	/**
	 * mev's derived per-block SDLC recency (`MV.10.D`), carried verbatim from
	 * `mev::brain::last_touched::derive_last_touched` — `serve` derives nothing
	 * itself. **Absence means "never worked", not "worked long ago"**: a block
	 * with no resolvable SDLC run has no entry in mev's map and this field is
	 * `None`. Unlike the v0.11 sibling fields above (`wave`/`priority`/`due`/
	 * `track`, which serialise as `null`), this field deliberately carries
	 * `skip_serializing_if` so `None` serialises as an **absent key** rather
	 * than `null` — the block's stated backward-compatibility contract.
	 */
	last_touched?: string;
	/**
	 * Corpus-wide count of in-corpus blocks whose `BlockedBy` edges point at this
	 * block, carried **verbatim** from mev's `BlockGraphNode::dependent_count`
	 * (`../mev/src/brain/block_graph.rs:204`) — `serve` derives nothing itself.
	 * Computed over the full corpus before any scope filtering, so it is
	 * **identical for a given block whether the board is fetched at `hq` scope or
	 * a narrower tier/project scope** (see `../mev/src/brain/block_graph.rs:110-113`)
	 * — this is the property bastion-web's in-scope reverse-dep count
	 * (`lib/board-view.ts:669-676`) structurally cannot have, and the entire
	 * justification for shipping this field. `None` means the block was **absent
	 * from the graph export** (truncated by `max_nodes`, or filtered out of scope
	 * entirely) — never a fabricated zero; mev's own `dependent_count` is `0` for a
	 * block nothing depends on, so `Some(0)` and `None` are deliberately distinct.
	 */
	dependent_count?: number;
	/**
	 * Membership in mev's `ready_order` set, carried verbatim from
	 * `BlockGraphNode::ready`. **This is the readiness signal consumers should
	 * use** — not `unmet_count == 0` (see that field's doc comment). `None` means
	 * the block was absent from the graph export, never a fabricated `false`.
	 */
	ready?: boolean;
	/**
	 * Count of unmet dependencies, carried verbatim from
	 * `BlockGraphNode::unmet_count`, but populated **only for blocked-lane
	 * entries**. mev defines `unmet_count` as `0` for every non-blocked lane
	 * (`../mev/src/brain/block_graph.rs:104-106`) — that is a structural zero, not
	 * a measurement, so projecting it unqualified onto `now`/`next`/`deferred`/
	 * `finished` blocks would let a consumer read "0 unmet ⇒ ready" and reproduce,
	 * server-blessed, the exact false-ready bug this enrichment exists to kill.
	 * **Consumers must use `ready`, never `unmet_count == 0`, as the readiness
	 * check.** `None` on the blocked lane means the block was absent from the
	 * graph export; `None` on every other lane is the field's normal, permanent
	 * state.
	 */
	unmet_count?: number;
}

/** The four now/next/blocked/finished lanes for one board (aggregate or per-repo). */
export interface BoardLaneDto {
	/** Blocks currently in progress. */
	now?: BoardBlockDto[];
	/** Blocks queued for next (ordered). */
	next?: BoardBlockDto[];
	/** Blocks waiting on something. */
	blocked?: BoardBlockDto[];
	/**
	 * Blocks deliberately parked on the back burner (authored `status == "deferred"`).
	 * 
	 * Real roadmap work that is not being surfaced as next. Never overlaps
	 * `next` — a deferred block is structurally excluded from ready-order — and
	 * never overlaps `blocked`, even when it carries unmet deps.
	 */
	deferred?: BoardBlockDto[];
	/** Blocks whose `status == "closed"`. */
	finished?: BoardBlockDto[];
}

/** One repo's lane breakdown within a `scope=project` board response. */
export interface RepoBoardDto {
	/** Repo slug. */
	repo: string;
	/** Tier classification, when known (e.g. `"core"`, `"business"`). */
	tier?: string;
	/** This repo's own four lanes. */
	lanes: BoardLaneDto;
}

/** JSON response for `GET /api/board?scope=hq|tier|project|business[&tier=<name>]`. */
export interface BoardDto {
	/** The resolved scope this response was projected under. */
	scope?: BoardScope;
	/** The resolved tier name, when `scope` is tier-scoped (`None` for `hq`). */
	tier?: string;
	/** Aggregate lanes across all in-scope repos. */
	lanes: BoardLaneDto;
	/** Per-project lane breakdown (populated for `scope=project`; empty otherwise). */
	repos?: RepoBoardDto[];
	/**
	 * Freshness flag: `true` when any in-scope repo's `status.md` cache lags
	 * its `state.json` (derived from `mev::brain::sync::check_sync`).
	 */
	stale: boolean;
}

/**
 * Detail of a breached budget cap — mirrors `costs::budget::BreachReason`.
 * 
 * `cap` carries `Cap::as_str`'s exact strings (`"max_total_tokens"` /
 * `"max_cost_usd"`), matching what the Engine stamps into
 * `metadata.budget.reason.cap` (contract v1.1.0 §5).
 */
export interface BudgetBreachDto {
	/** Which cap was breached: `"max_total_tokens"` or `"max_cost_usd"`. */
	cap: string;
	/** The spend value that tripped the cap. */
	spent: number;
	/** The configured limit that was reached. */
	limit: number;
}

/**
 * Budget configuration + current gate state for the aggregated window.
 * 
 * Read-only projection: caps are reported as configured (from `Config`), not
 * mutated over HTTP — budget mutation stays CLI/D48. A run with no caps
 * configured (`Budget::default()`) always reports `breached: false`.
 */
export interface BudgetStateDto {
	/** Configured token cap, when set. */
	max_total_tokens?: number;
	/** Configured USD cost cap, when set. */
	max_cost_usd?: number;
	/** Current total tokens spent (`tokens_in + tokens_out`) for the window. */
	total_tokens: number;
	/** Current total USD cost for the window. */
	total_cost_usd: number;
	/**
	 * Whether any configured cap has been reached (`>=`, per `evaluate`'s
	 * documented boundary).
	 */
	breached: boolean;
	/** Which cap was breached and by how much, when `breached` is `true`. */
	breach?: BudgetBreachDto;
}

/**
 * Dispatch mode for `POST /actions/command`.
 * 
 * Serializes/deserializes as the lowercase wire string (`"inject"` / `"spawn"`).
 */
export enum CommandMode {
	/** Send the command into an existing tmux session. */
	Inject = "inject",
	/** Create a new session, launch `claude`, wait for readiness, then send the command. */
	Spawn = "spawn",
}

/**
 * Request body for `POST /actions/command`.
 * 
 * Wire format (inject):
 * ```json
 * { "mode": "inject", "session": "main", "command": "/status" }
 * ```
 * 
 * Wire format (spawn):
 * ```json
 * { "mode": "spawn", "name": "work", "dir": "/repo", "model": "sonnet", "command": "/status" }
 * ```
 * 
 * Field requirements are mode-dependent and enforced by [`CommandRequest::validate`],
 * not by serde: `session` is required for `inject`; `name` is required for `spawn`;
 * `model`, when present, must be one of [`ALLOWED_COMMAND_MODELS`].
 */
export interface CommandRequest {
	/** Dispatch mode: `"inject"` or `"spawn"`. */
	mode: CommandMode;
	/** Target tmux session name. Required when `mode:"inject"`. */
	session?: string;
	/** Name for the new tmux session. Required when `mode:"spawn"`. */
	name?: string;
	/** Optional starting directory for a spawned session. */
	dir?: string;
	/** Optional Claude model for a spawned session; one of [`ALLOWED_COMMAND_MODELS`]. */
	model?: string;
	/** The slash command (or literal text) to send once the target session is ready. */
	command: string;
}

/**
 * Response body for `POST /actions/command`.
 * 
 * Wire format: `{ "session": "work" }`
 */
export interface CommandResponse {
	/** The target tmux session id (existing for inject, newly created for spawn). */
	session: string;
}

/** A single contact channel bundle for an opportunity. */
export interface ContactDto {
	name?: string;
	role?: string;
	emails?: string[];
	whatsapp?: string[];
	phones?: string[];
	links?: string[];
	note?: string;
}

/**
 * One per-workflow aggregated cost row — mirrors `costs::WorkflowCost` exactly.
 * 
 * Wire format:
 * `{ "workflow_name": "content-pipeline", "runs": 12, "tokens_in": 48000, "tokens_out": 9000, "usd": 1.32 }`
 */
export interface WorkflowCostDto {
	/** Distinct workflow name this row aggregates. */
	workflow_name: string;
	/** Number of runs contributing to this row. */
	runs: number;
	/** Total input tokens across the contributing runs. */
	tokens_in: number;
	/** Total output tokens across the contributing runs. */
	tokens_out: number;
	/** Total USD cost across the contributing runs. */
	usd: number;
}

/**
 * `GET /api/costs` response body — read-only projection of `costs::CostSummary`
 * plus the BA.7.C budget state for the resolved window.
 * 
 * Wire format:
 * ```json
 * {
 * "window": "7d",
 * "rows": [{ "workflow_name": "content-pipeline", "runs": 12, "tokens_in": 48000, "tokens_out": 9000, "usd": 1.32 }],
 * "totals": { "workflow_name": "TOTAL", "runs": 12, "tokens_in": 48000, "tokens_out": 9000, "usd": 1.32 },
 * "unpriced_models": [],
 * "budget": { "max_total_tokens": null, "max_cost_usd": null, "total_tokens": 57000, "total_cost_usd": 1.32, "breached": false, "breach": null }
 * }
 * ```
 */
export interface CostSummaryDto {
	/** The resolved window echoed back to the client (`"7d"` / `"30d"` / `"all"`). */
	window: string;
	/** One row per distinct `workflow_name`, sorted by `usd` descending. */
	rows?: WorkflowCostDto[];
	/** Totals across all rows. */
	totals: WorkflowCostDto;
	/**
	 * Model IDs that appeared in the data but have no price entry — spend is
	 * under-reported for these rather than silently omitted.
	 */
	unpriced_models?: string[];
	/** Budget configuration + current gate state for this window. */
	budget: BudgetStateDto;
}

/**
 * One entry in a `GET /api/docs/{repo}/tree` listing.
 * 
 * Wire format:
 * ```json
 * { "path": "planning/status.md", "name": "status.md", "is_dir": false }
 * ```
 */
export interface DocEntryDto {
	/** Repo-root-relative path — exactly what `GET /api/docs/{repo}/file`'s `?path=` accepts. */
	path: string;
	/** The entry's base name (final path component). */
	name: string;
	/** `true` when the entry is a directory, `false` for a file. */
	is_dir: boolean;
}

/**
 * JSON response for `GET /api/docs/{repo}/file?path=<rel-file>`.
 * 
 * Wire format:
 * ```json
 * {
 * "repo": "bastion",
 * "path": "planning/status.md",
 * "content": "---\ntype: Status\n---\n\n# bastion — Status\n…",
 * "bytes": 8421,
 * "modified": "2026-07-24T18:03:11Z"
 * }
 * ```
 */
export interface DocFileDto {
	/** Echoes the resolved workspace registry name. */
	repo: string;
	/** The validated, repo-root-relative path that was read. */
	path: string;
	/**
	 * The file's raw markdown, byte-for-byte — no rendering, no frontmatter stripping, no
	 * sentinel removal.
	 */
	content: string;
	/** Content length in bytes. */
	bytes: number;
	/** Filesystem mtime, RFC 3339 UTC; `None` when unavailable. */
	modified?: string;
}

/**
 * JSON response for `GET /api/docs/{repo}/tree?path=<rel-dir>`.
 * 
 * Wire format:
 * ```json
 * {
 * "repo": "bastion",
 * "root": "planning",
 * "entries": [
 * { "path": "planning/status.md", "name": "status.md", "is_dir": false },
 * { "path": "planning/decisions", "name": "decisions", "is_dir": true }
 * ]
 * }
 * ```
 */
export interface DocTreeDto {
	/** Echoes the resolved workspace registry name. */
	repo: string;
	/**
	 * The allowlisted root (or subtree) the listing is relative to; `""` when the whole
	 * allowlist was walked.
	 */
	root: string;
	/** Sorted directories-first, then by `name`. Only markdown-bearing entries appear. */
	entries?: DocEntryDto[];
}

/**
 * One entry in the HQ brain's `epics[]` cross-repo initiative registry —
 * the wire projection of `okf_core::Epic`.
 * 
 * The registry is HQ-only (D2 precedent, same as `backlog[]`): it is the closed
 * vocabulary a block's `epics[]` membership is validated against by
 * `mev validate-brain`. Membership itself is authored on the blocks, not here —
 * `repos` is a human hint, not the source of truth.
 * 
 * Wire format:
 * `{ "slug": "bastion-surfaces", "title": "Bastion Surfaces", "description": "…", "status": "active", "plan": "core/planning/master-plan.md", "repos": ["bastion", "bastion-web"] }`
 */
export interface EpicDto {
	/** Stable kebab-case key — the value blocks reference in their `epics[]`. */
	slug: string;
	/** Human-readable name (e.g. `"Bastion OS"`). */
	title: string;
	/** One-line description of what the initiative covers. */
	description?: string;
	/** Lifecycle: `"active"` · `"paused"` · `"complete"`. */
	status?: string;
	/**
	 * Authored initiative weight, carried verbatim from `okf_core::Epic.weight`.
	 * 
	 * Range policy (`0..=100`) is mev's, enforced by its `check_epics`
	 * (`E_STATE_EPIC_BAD_WEIGHT`) — bastion never clamps, defaults, or
	 * range-checks it, so an out-of-policy authored value reaches the wire
	 * unchanged rather than being silently corrected here.
	 * 
	 * `null` on the wire means unauthored (a consumer default applies —
	 * bastion-web currently falls back to 60), which stays distinguishable
	 * from an authored `0`.
	 */
	weight?: number;
	/** Repo-relative path to the owning master-plan / plan doc, when one exists. */
	plan?: string;
	/** Repos the initiative is expected to touch — an authored hint for readers. */
	repos?: string[];
	/** Member blocks with authored `status == "closed"`. */
	closed?: number;
	/** Member blocks with authored `status == "in_progress"`. */
	in_progress?: number;
	/** Member blocks that are open (authored `open`, or status absent). */
	open?: number;
	/** Member blocks with authored `status == "deferred"`. */
	deferred?: number;
	/** Every member block, in any state. `0` means the epic has no members yet. */
	total?: number;
	/**
	 * Is this epic's remaining work entirely parked?
	 * 
	 * True iff it has at least one deferred member and no unfinished
	 * non-deferred work. An epic whose members are all `closed` is *complete*,
	 * not deferred, so this stays false for it.
	 * 
	 * Lets a Surface render "this whole initiative is parked" on load, instead
	 * of drawing four empty lane columns and leaving the reader to infer it.
	 */
	fully_deferred?: boolean;
}

/**
 * Payload shape for `WsFrameKind::Error` frames.
 * 
 * Allows the server to surface typed error information over the WS channel.
 */
export interface ErrorPayload {
	/** Short machine-readable error code (e.g. `"C001"`). */
	code: string;
	/** Human-readable error message. */
	message: string;
}

/**
 * Payload for server→client `event` frames (e.g. `needs_input`).
 * 
 * Wire format: `{ "session": "main", "event": "needs_input" }`
 */
export interface EventPayload {
	/** Session that triggered the event. */
	session: string;
	/** Event name; currently only `"needs_input"` is defined. */
	event: string;
}

/**
 * JSON response for `GET /repos/{name}/handoff`.
 * 
 * Mirrors [`crate::serve::status::handoff::HandoffInfo`] field-for-field — kept
 * as an independent DTO (per this module's doc comment) rather than reusing
 * the domain type directly.
 */
export interface HandoffInfoDto {
	/**
	 * Title — frontmatter `title:` scalar if present, else the text after
	 * the first `# Handoff —`/`# Handoff -` heading, else an empty string.
	 */
	title: string;
	/** The full raw markdown content (including frontmatter, if any). */
	body: string;
}

/**
 * JSON body returned by `GET /health`.
 * 
 * Matches the shape documented in `docs/serve-api.md` v0:
 * ```json
 * { "status": "ok", "service": "bastion" }
 * ```
 */
export interface HealthResponse {
	/** Liveness status; always `"ok"` when the server is healthy. */
	status: string;
	/** Service identifier; always `"bastion"`. */
	service: string;
}

/**
 * Request body for `POST /api/sessions/{name}/key`.
 * 
 * Sends a single named tmux key (e.g. `"Escape"`, `"Up"`, `"C-c"`) without
 * the `-l` flag so tmux resolves the symbolic key name.
 * 
 * Wire format: `{ "key": "Escape" }`
 * 
 * Accepted key names include: `Escape`, `Enter`, `Up`, `Down`, `Left`,
 * `Right`, and modifier combinations such as `C-c`.
 */
export interface KeyBody {
	/** Symbolic tmux key name to send (e.g. `"Escape"`, `"Up"`, `"C-c"`). */
	key: string;
}

/**
 * Request body for `POST /api/sessions` (create a new tmux session).
 * 
 * Wire format: `{ "name": "mysession", "dir": "/optional/start/dir" }`
 */
export interface NewSessionBody {
	/** Name of the new tmux session to create. */
	name: string;
	/** Optional starting directory for the session. */
	dir?: string;
}

/**
 * Token/model usage for an LLM node, projected from `engine_contract::task_context::Usage`.
 * 
 * Wire format:
 * ```json
 * { "input_tokens": 512, "output_tokens": 128, "model": "claude-sonnet-5" }
 * ```
 */
export interface RunUsageDto {
	/** Prompt token count, when reported by the provider. */
	input_tokens?: number;
	/** Completion token count, when reported by the provider. */
	output_tokens?: number;
	/** Model identifier used for this node's LLM call. */
	model: string;
}

/**
 * One node's projected run state — the join of `TaskContext::node_runs[class]`
 * (status/timing/error/input/usage) with `TaskContext::nodes[class]` (output),
 * keyed by the node's class name (BA.11.M).
 * 
 * Wire format:
 * ```json
 * {
 * "node": "DataIngestionNode",
 * "status": "success",
 * "started_at": "2026-07-24T12:00:00Z",
 * "completed_at": "2026-07-24T12:00:01Z",
 * "error": null,
 * "input": null,
 * "output": { "documents_loaded": 3 },
 * "usage": null
 * }
 * ```
 */
export interface NodeTransitionDto {
	/**
	 * Node identity — the Python class name (contract §1), used as the map key
	 * in both `TaskContext::nodes` and `TaskContext::node_runs`.
	 */
	node: string;
	/** Lifecycle status as the lowercase wire string: `pending`/`running`/`success`/`failed`. */
	status: string;
	/** ISO-8601 UTC timestamp set on entry, `null` while pending. */
	started_at?: string;
	/** ISO-8601 UTC timestamp set on success or failure, `null` before completion. */
	completed_at?: string;
	/** Error message, present only for a `failed` node. */
	error?: string;
	/** The node's recorded input, present only for a `failed` node. */
	input?: any;
	/** The node's output value from `TaskContext::nodes`, `null` when not yet produced. */
	output?: any;
	/** Token/model usage, present only for LLM nodes. */
	usage?: RunUsageDto;
}

/** One entry in an opportunity's `actions` activity log. */
export interface OpportunityActionDto {
	/** Date/timestamp of the action (e.g. `2026-07-25`). */
	at: string;
	/** Action kind (e.g. `research`, `outreach`). */
	kind: string;
	/** Free-text note. */
	note: string;
}

/** One prospect archetype inside a ProspectingResult research brief. */
export interface ProspectLeadDto {
	name: string;
	pillar: string;
	pain_points?: string[];
	outreach_hook?: string;
	source?: string;
}

/**
 * The research brief embedded in an opportunity body's first ```json fence.
 * 
 * `kind` is `"company"` (a CompanyBrief — has `company_name`) or
 * `"prospecting"` (a ProspectingResult — has `prospects`/`vertical`); the two
 * families' fields are unioned so a single DTO covers both, with the unused
 * family's fields left empty/`None`.
 */
export interface ResearchBriefDto {
	/** `"company"` or `"prospecting"`. */
	kind: string;
	company_name?: string;
	summary?: string;
	recent_developments?: string[];
	pain_points?: string[];
	outreach_hooks?: string[];
	sources?: string[];
	vertical?: string;
	common_pain_points?: string[];
	prospects?: ProspectLeadDto[];
}

/** The full projection for one opportunity (`GET /api/pipeline/{slug}`). */
export interface OpportunityDetailDto {
	/** File stem (e.g. `anthropic`). */
	slug: string;
	/** `kind` frontmatter; defaults to `company` when absent. */
	kind: string;
	/** `title` frontmatter (falls back to `slug` when absent). */
	title: string;
	/** `source` frontmatter, when present. */
	source?: string;
	/** `stage` frontmatter, when present. */
	stage?: string;
	/** `last_contact` frontmatter, when present. */
	last_contact?: string;
	/** `next_action` frontmatter, when present. */
	next_action?: string;
	/** `url` frontmatter, when present. */
	url?: string;
	/** `links` frontmatter list. */
	links?: string[];
	/** `research_ref` frontmatter, when present. */
	research_ref?: string;
	/** `contacts` frontmatter list. */
	contacts?: ContactDto[];
	/** The research brief parsed from the body's first ```json fence, when present. */
	findings?: ResearchBriefDto;
	/** `actions` frontmatter list (activity log). */
	actions?: OpportunityActionDto[];
	/** The markdown body (everything after the frontmatter block), when non-empty. */
	body_markdown?: string;
}

/** A single opportunity, projected for the list view (`GET /api/pipeline`). */
export interface OpportunitySummaryDto {
	/** File stem (e.g. `anthropic`) — the `{slug}` for the detail route. */
	slug: string;
	/**
	 * `kind` frontmatter (`company` | `prospecting-sweep` | `job-posting`);
	 * defaults to `company` when absent.
	 */
	kind: string;
	/** `title` frontmatter (falls back to `slug` when absent). */
	title: string;
	/** `source` frontmatter, when present. */
	source?: string;
	/** `stage` frontmatter, when present. */
	stage?: string;
	/** `last_contact` frontmatter, when present. */
	last_contact?: string;
	/** `next_action` frontmatter, when present. */
	next_action?: string;
	/** Whether the body carries a parseable research brief (```json fence). */
	has_findings: boolean;
}

/**
 * JSON response for `GET /api/sessions/{name}/pane`.
 * 
 * Wire format:
 * ```json
 * { "session_name": "main", "lines": ["line1", "line2"] }
 * ```
 */
export interface PaneDto {
	/** tmux session name this pane belongs to. */
	session_name: string;
	/** Lines of captured pane output (trailing blank padding stripped). */
	lines: string[];
}

/**
 * Payload for server→client `pane` frames (pane diff push).
 * 
 * Wire format: `{ "session": "main", "seq": 42, "lines": ["line1", "line2"] }`
 */
export interface PanePayload {
	/** tmux session name whose pane was captured. */
	session: string;
	/** Monotonically increasing sequence number; bumped on every diff push. */
	seq: number;
	/** Non-blank trailing lines from the captured pane output. */
	lines: string[];
}

/**
 * JSON response for `GET /api/pipeline`.
 * 
 * `stages` is the canonical stage vocabulary/order parsed from
 * `business/docs/pipeline.md`'s `## Stages` line; `opportunities` are the
 * per-file summaries, sorted by stage order (index in `stages`, unknown/none
 * last) then title.
 */
export interface PipelineDto {
	/** Canonical stage vocabulary in pipeline order. */
	stages?: string[];
	/** One summary per opportunity file (opportunities + leads). */
	opportunities?: OpportunitySummaryDto[];
}

/**
 * JSON response for `GET /repos/{name}/status`.
 * 
 * Mirrors [`crate::serve::status::repo::RepoStatus`] field-for-field — kept
 * as an independent DTO (per this module's doc comment) rather than reusing
 * the domain type directly.
 */
export interface RepoStatusDto {
	/** Workspace registry name. */
	name: string;
	/** Frontmatter `now:` scalar. */
	now: string;
	/** Frontmatter `next:` scalar. */
	next: string;
	/** Frontmatter `blocked:` scalar. */
	blocked: string;
	/** Whether `planning/handoff.md` exists. */
	has_handoff: boolean;
	/** Body `## Momentum` → `now` queue line text. */
	momentum_now: string;
	/** Body `## Momentum` → `next` queue line text. */
	momentum_next: string;
	/** Body `## Momentum` → `blocked` queue line text. */
	momentum_blocked: string;
	/** Body `## Momentum` → `improve` queue line text. */
	momentum_improve: string;
	/** Body `## Momentum` → `recurring` queue line text. */
	momentum_recurring: string;
}

/**
 * JSON response element for `GET /repos` (one per workspace registry entry).
 * 
 * Wire format: `{ "name": "bastion", "now": "BA.11.D in progress", "has_handoff": false }`
 */
export interface RepoSummaryDto {
	/** Workspace registry name. */
	name: string;
	/** Frontmatter `now:` scalar from the repo's `planning/status.md`. */
	now: string;
	/** Whether `planning/handoff.md` exists for this workspace. */
	has_handoff: boolean;
}

/**
 * JSON response element for `GET /api/workflows` — one [`WorkflowStateDto`]
 * tagged with the repo it belongs to.
 * 
 * `WorkflowStateDto` carries `spec_slug` but no repo dimension: in the
 * per-repo route (`GET /repos/{name}/workflows`) the repo is implied by the
 * path, but flattened across every registered repo it is not — two repos can
 * legitimately hold the same `spec_slug`, so a bare list of `WorkflowStateDto`
 * would be ambiguous. This wrapper makes the repo dimension explicit.
 * 
 * **Shape note:** the natural encoding here would be
 * `{ repo: String, #[serde(flatten)] state: WorkflowStateDto }`, but
 * `typeshare` 1.13 does not support `#[serde(flatten)]` — it is a hard parse
 * error ("The serde flatten attribute is not currently supported"), verified
 * empirically against this exact shape before choosing the fallback below.
 * So this struct mirrors `WorkflowStateDto`'s fields directly rather than
 * composing it; the duplication is forced by the typeshare toolchain, not a
 * design choice. If `WorkflowStateDto` gains or changes a field, mirror the
 * change here too — the `From<(String, WorkflowStateDto)>` impl below will
 * fail to compile if the two drift, since it destructures `WorkflowStateDto`
 * by name.
 */
export interface RepoWorkflowStateDto {
	/** The registered workspace name this flow state belongs to. */
	repo: string;
	spec_slug: string;
	branch: string;
	/** Raw status string, e.g. `"running"`, `"done"`, `"blocked"`. */
	status: string;
	current_task: number;
	started_at: string;
	updated_at: string;
	/**
	 * See [`WorkflowStateDto::run_id`] — same semantics, same
	 * absent-key-when-`None` serialization.
	 */
	run_id?: string;
}

/**
 * JSON response for `GET /api/runs/{id}` — the projected `LiveStateStore` snapshot
 * for one run (BA.11.M).
 * 
 * Wire format:
 * ```json
 * {
 * "run_id": "b6a1...",
 * "event": { "ticket_id": "T-1" },
 * "metadata": { "workflow": "sdlc-flow" },
 * "nodes": [ { "node": "DataIngestionNode", "status": "success", ... } ]
 * }
 * ```
 */
export interface RunStateDto {
	/** The run's UUID as a string. */
	run_id: string;
	/** The triggering event payload, carried through from `TaskContext::event`. */
	event: any;
	/** Workflow-level metadata, carried through from `TaskContext::metadata`. */
	metadata: any;
	/** Per-node projected states, one entry per class name in `TaskContext::node_runs`. */
	nodes: NodeTransitionDto[];
}

/**
 * Payload for the server→client `event{run_stream_status}` WS push.
 * 
 * Sent inside an [`EventPayload`]-shaped frame: the `event` field is fixed
 * to `"run_stream_status"` and the extra `available`/`reason` fields are
 * flattened into the same JSON object by the caller. Pushed immediately to
 * a connection when it subscribes to the `runs` topic, before any
 * `run_transition` frame (D17 constraint 2).
 * 
 * Wire format: `{ "available": true }` or
 * `{ "available": false, "reason": "DATABASE_URL not set" }`.
 * 
 * `available: false` means the engine was not mounted for this `bastion
 * serve` process, so `LiveStateStore` can never be written and no
 * `run_transition` frame will ever arrive on this connection — the client
 * must fall back to polling `GET /api/runs` / `GET /api/runs/{id}`, which
 * remain the source of truth regardless of `runs`-topic availability (D17
 * constraints 2 and 3).
 */
export interface RunStreamStatusPayload {
	/**
	 * Whether the `runs` topic can ever emit a `run_transition` frame on
	 * this connection (i.e. whether the engine is mounted).
	 */
	available: boolean;
	/**
	 * Human-readable reason when `available` is `false`. Absent (not
	 * `null`) when `available` is `true`.
	 */
	reason?: string;
}

/**
 * One live run's summary projection — `GET /api/runs` (BA.11.T).
 * 
 * A widened successor to the bare-UUID `Vec<String>` `GET /api/runs` used to return: each
 * entry now carries enough to render a live-runs band (spec slug, derived status, timing)
 * without an N+1 `GET /api/runs/{id}` fetch per run.
 * 
 * Wire format (both variants — `spec_slug` present vs. omitted):
 * ```json
 * {
 * "run_id": "b6a1c1e0-0000-4000-8000-000000000000",
 * "status": "running",
 * "spec_slug": "11.T-run-summary-projection",
 * "started_at": "2026-07-24T12:00:00Z",
 * "updated_at": "2026-07-24T12:00:01Z"
 * }
 * ```
 * ```json
 * {
 * "run_id": "c7b2d2f1-0000-4000-8000-000000000000",
 * "status": "pending",
 * "started_at": null,
 * "updated_at": null
 * }
 * ```
 */
export interface RunSummaryDto {
	/** The run's UUID as a string. */
	run_id: string;
	/**
	 * Workflow identity (e.g. `"sdlc-flow"`). **Always absent today** — no production code
	 * stamps a workflow-identity key anywhere `bastion` can read it from a live `TaskContext`;
	 * `engine-serve` only tracks it in a process-local, `pub(crate)`-scoped side table. Tracked
	 * by the engine-rs follow-up ticket `EN.ticket.expose-live-run-workflow-type`
	 * (`core/engine-rs/planning/ticket-expose-live-run-workflow-type/`); this DTO does not
	 * fabricate a value in the meantime.
	 */
	workflow_type?: string;
	/**
	 * Lifecycle status as the lowercase wire string, derived via
	 * `db::workflows::derive_run_status`: `pending`/`running`/`success`/`failed`/
	 * `cancelled`/`budget_halted`/`suspended` (v0.17). `suspended` is not
	 * terminal — a resumed run falls back through to the other rules.
	 */
	status: string;
	/**
	 * The triggering event's `spec_slug` field, when present. Omitted (not `null`) when the
	 * run's event carries no `spec_slug` key.
	 */
	spec_slug?: string;
	/**
	 * Earliest non-null `node_runs[*].started_at` across all tracked nodes, as RFC3339.
	 * `null` when the run has no recorded node transitions yet.
	 */
	started_at?: string;
	/**
	 * Latest non-null `node_runs[*].started_at` **or** `completed_at` across all tracked
	 * nodes, as RFC3339. `null` when the run has no recorded node transitions yet.
	 */
	updated_at?: string;
	/**
	 * The repo that owns this run, resolved by an **exact `run_id` match** against the
	 * registry's flow state (`RepoWorkflowStateDto` from `collect_all_workflows`, A2). Absent
	 * (never `null`) when no flow state carries this run's `run_id` — the run could not be
	 * attributed to a repo. A wrong label would be strictly worse than an absent one, so this
	 * field is never guessed via substring, prefix, or spec-slug similarity matching (A7).
	 * Only populated when the request opts in via `?with_repo=1`; otherwise always absent, to
	 * keep the unopted poll path free of the registry walk that resolving `repo` requires.
	 */
	repo?: string;
}

/**
 * Payload for the server→client `event{run_transition}` WS push.
 * 
 * Sent inside an [`EventPayload`]-shaped frame: the `event` field is fixed
 * to `"run_transition"` and the extra `run_id`/`status`/`terminal`/`spec_slug`
 * fields are flattened into the same JSON object by the caller (`runs`-topic
 * WS wiring, `src/serve/ws/server.rs`).
 * 
 * Wire format: `{ "run_id": "…", "status": "running", "terminal": false }`
 * (`spec_slug` present only when known).
 * 
 * `terminal` means **lifecycle**-terminal — the run left `LiveStateStore`'s
 * live map (`list_active()` no longer returns its id) — not "wire-terminal"
 * in the engine's own `publish_suspended` sense. A suspended run is still in
 * the live map, so it is reported as `status: "suspended"` paired with
 * `terminal: false`; only a run's genuine disappearance from the live set
 * (completed, failed, or otherwise retired into the completed ring) emits
 * `terminal: true` (D17 constraint 1).
 */
export interface RunTransitionPayload {
	/** The run's UUID, as a string. */
	run_id: string;
	/**
	 * Aggregate run status string, from `db::workflows::derive_run_status`
	 * via `run_status_str` — the same derivation `GET /api/runs` uses.
	 */
	status: string;
	/**
	 * `true` only when the run has left `LiveStateStore`'s live map
	 * (lifecycle-terminal); `false` for every live-map status, including
	 * `"suspended"`.
	 */
	terminal: boolean;
	/**
	 * `sdlc-flow-state.json` spec slug, when known. Absent (not `null`)
	 * when unknown, matching the repo's established DTO convention.
	 */
	spec_slug?: string;
}

/**
 * Request body for `POST /api/sessions/{name}/send`.
 * 
 * Sends a literal string of keystrokes to the session followed by `Enter`.
 * Wire format: `{ "keys": "cargo test" }`
 */
export interface SendBody {
	/** Literal text to send to the session (forwarded with `-l`). */
	keys: string;
}

/**
 * Payload for client→server `send_key` frames (single named tmux key).
 * 
 * Wire format: `{ "session": "main", "key": "Escape" }`
 */
export interface SendKeyPayload {
	/** Target tmux session name. */
	session: string;
	/** Symbolic tmux key name (e.g. `"Escape"`, `"Up"`, `"C-c"`). */
	key: string;
}

/**
 * Payload for client→server `send` frames (literal keystrokes + Enter).
 * 
 * Wire format: `{ "session": "main", "keys": "cargo test" }`
 */
export interface SendPayload {
	/** Target tmux session name. */
	session: string;
	/** Literal text to send (forwarded with `-l`), followed by Enter. */
	keys: string;
}

/**
 * JSON response for a single tmux session (one element of `GET /api/sessions`).
 * 
 * Wire format:
 * ```json
 * { "name": "main", "state": "running", "last_line": "$ cargo test" }
 * ```
 */
export interface SessionDto {
	/** tmux session name. */
	name: string;
	/** Session state as a string: `"running"` or `"idle"`. */
	state: string;
	/** Last non-blank line from the session's pane, or empty string when unavailable. */
	last_line: string;
}

/**
 * Payload for server→client `sessions` frames (session list snapshot).
 * 
 * Wire format: `{ "sessions": [ … ] }`
 */
export interface SessionsPayload {
	/** Current snapshot of all tmux sessions. */
	sessions: SessionDto[];
}

/**
 * One registered workspace that `GET /api/workflows?with_skipped=1`
 * could not fully report on.
 * 
 * Returned only inside [`WorkflowsAggregateDto::skipped`] — the default,
 * no-query-param response of `GET /api/workflows` never includes this type.
 * `reason` is a plain `String` on the wire (one of `"unreadable_root"` |
 * `"no_planning_dir"` | `"malformed_flow_state"`), matching how
 * [`RepoWorkflowStateDto::status`] carries a raw status string rather than
 * an enum. See serve-api §11.6 for the full vocabulary, the
 * first-match-wins precedence order, and the "empty is not skipped" rule.
 */
export interface SkippedWorkspaceDto {
	/** The registered workspace name whose report is incomplete. */
	repo: string;
	/** One of `"unreadable_root"`, `"no_planning_dir"`, `"malformed_flow_state"`. */
	reason: string;
}

/**
 * Payload for client→server `subscribe` / `unsubscribe` frames.
 * 
 * Wire format: `{ "topic": "sessions" }` or `{ "topic": "pane:work" }`
 */
export interface SubscribePayload {
	/** Topic string: `"sessions"` or `"pane:<name>"`. */
	topic: string;
}

/**
 * Payload for the server→client `event{workflow_done}` WS push.
 * 
 * Sent inside an [`EventPayload`]-shaped frame: the `event` field is fixed
 * to `"workflow_done"` and the extra repo/spec_slug/status fields are
 * flattened into the same JSON object by the caller (Task 4 WS wiring).
 * 
 * Wire format: `{ "repo": "bastion", "spec_slug": "phase11-blockD", "status": "done" }`
 */
export interface WorkflowDonePayload {
	/** Workspace registry name the workflow belongs to. */
	repo: string;
	/** `sdlc-flow-state.json` spec slug. */
	spec_slug: string;
	/** The terminal status that triggered the event (`"done"` or `"blocked"`). */
	status: string;
}

/**
 * JSON response element for `GET /repos/{name}/workflows`.
 * 
 * Serializable projection of [`crate::serve::status::flow::FlowState`].
 */
export interface WorkflowStateDto {
	spec_slug: string;
	branch: string;
	/** Raw status string, e.g. `"running"`, `"done"`, `"blocked"`. */
	status: string;
	current_task: number;
	started_at: string;
	updated_at: string;
	/**
	 * The engine's `events.id` run UUID that produced this write, stamped by
	 * engine-rs `EN.6.J` into the top-level `run_id` key of
	 * `sdlc-flow-state.json`. `None` for states written before that fix and
	 * for any state written by base-template's JS `sdlc-flow.js` engine,
	 * which never sets it. Deliberately carries `skip_serializing_if` (the
	 * `BoardBlockDto.last_touched` precedent) so `None` serialises as an
	 * **absent key** rather than `null` — a consumer must be able to
	 * distinguish "this run predates the stamp" from "field not understood".
	 */
	run_id?: string;
}

/**
 * The `?with_skipped=1` envelope for `GET /api/workflows`.
 * 
 * Returned ONLY when the request carries `?with_skipped=1` — the bare-array
 * default response of `GET /api/workflows` is unchanged from v0.23 and does
 * not use this type. `entries` carries the same [`RepoWorkflowStateDto`]
 * list the default response returns, in the same order; `skipped` names
 * every registered workspace whose flow-state report is incomplete, and
 * why. Both fields always serialize, including when empty (`[]`, never an
 * absent key), so a consumer never has to distinguish absent-vs-empty.
 */
export interface WorkflowsAggregateDto {
	entries: RepoWorkflowStateDto[];
	skipped: SkippedWorkspaceDto[];
}

/**
 * Discriminant for [`WsFrame::kind`].
 * 
 * v0 defined `Echo` and `Error`.  v0.2 adds client→server kinds (`Subscribe`,
 * `Unsubscribe`, `Send`, `SendKey`) and server→client kinds (`Sessions`, `Pane`,
 * `Event`).
 */
export enum WsFrameKind {
	/** Echo — the `/ws` actor reflects the received frame back unchanged (v0). */
	Echo = "echo",
	/** Error — server-side error notification pushed to the client. */
	Error = "error",
	/** Subscribe to a topic (`sessions` or `pane:<name>`). */
	Subscribe = "subscribe",
	/** Unsubscribe from a topic. */
	Unsubscribe = "unsubscribe",
	/** Send literal keystrokes to a tmux session (followed by Enter). */
	Send = "send",
	/** Send a single named tmux key to a session (e.g. `"Escape"`, `"C-c"`). */
	SendKey = "send_key",
	/** Session list snapshot pushed to `sessions` subscribers. */
	Sessions = "sessions",
	/** Pane diff pushed to `pane:<name>` subscribers. */
	Pane = "pane",
	/** Async event pushed to all subscribed connections (e.g. `needs_input`). */
	Event = "event",
}

/**
 * Tagged WebSocket frame envelope.
 * 
 * Every WS message sent or received by `bastion serve` is wrapped in this
 * envelope so the Flutter client can dispatch on `kind` before parsing
 * `payload`.  This is the v0 skeleton; later blocks add concrete `kind`
 * variants and payload types.
 * 
 * Wire format (JSON):
 * ```json
 * { "kind": "echo", "payload": <any JSON value> }
 * ```
 */
export interface WsFrame {
	/** Frame type discriminant.  The Flutter client switches on this field. */
	kind: WsFrameKind;
	/** Arbitrary JSON payload.  Shape is defined per-kind in the serve-api contract. */
	payload: any;
}

