/*
 Generated by typeshare 1.13.4
*/

/**
 * One `backlog[]` node that has crossed the backlog staleness threshold — used for both the
 * `aging_backlog` lane (non-capture nodes) and the `orphaned_captures` lane (`origin.type ==
 * "capture"` nodes, never both).
 * 
 * Wire format:
 * ```json
 * { "repo": "bastion", "slug": "serve-attention-endpoint", "title": "Attention projection",
 * "kind": "feature", "status": "ready", "notes": null,
 * "created": "2026-07-10", "reviewed": null,
 * "age_days": 14, "threshold_days": 7 }
 * ```
 */
export interface AttentionBacklogDto {
	/** Owning repo slug. */
	repo: string;
	/** Stable item slug. */
	slug: string;
	/** Human-readable title. */
	title: string;
	/** Backlog kind (serde-renamed from `type` on the domain type). */
	kind: string;
	/** Lifecycle status (`"idea"` / `"ready"`, the only statuses that can age). */
	status: string;
	/**
	 * Notes; for `orphaned_captures` this is `origin.notes` falling back to the node's own
	 * `notes`.
	 */
	notes?: string;
	/** Creation date (`YYYY-MM-DD`), when recorded. */
	created?: string;
	/** Last-reviewed date (`YYYY-MM-DD`), when recorded. */
	reviewed?: string;
	/** Days past the anchor date (`max(created, reviewed)`), as of `as_of`. */
	age_days: number;
	/** The `backlog_days` threshold this item tripped. */
	threshold_days: number;
}

/**
 * One `carryover[]` entry that has crossed its per-`kind` staleness threshold.
 * 
 * Wire format:
 * ```json
 * { "repo": "bastion", "slug": "engine-mount-env", "kind": "env",
 * "text": "engine routes need DATABASE_URL + BASTION_ENGINE_API_KEY set",
 * "clears_when": "the engine mount is documented in .env.example",
 * "created": "2026-07-01", "reviewed": null,
 * "age_days": 23, "threshold_days": 3 }
 * ```
 */
export interface AttentionCarryoverDto {
	/** Owning repo slug. */
	repo: string;
	/** Stable item slug. */
	slug: string;
	/** Carryover kind (`"env"`, `"deferred"`, `"known_issue"`, `"constraint"`, or other). */
	kind: string;
	/** The carryover text itself, untruncated. */
	text: string;
	/** What clears this item, when recorded. */
	clears_when?: string;
	/** Creation date (`YYYY-MM-DD`), when recorded. */
	created?: string;
	/** Last-reviewed date (`YYYY-MM-DD`), when recorded. */
	reviewed?: string;
	/** Days past the anchor date (`max(created, reviewed)`), as of `as_of`. */
	age_days: number;
	/** The per-`kind` threshold this item tripped. */
	threshold_days: number;
}

/**
 * `scope` query param for `GET /api/board`.
 * 
 * Deserializes from the lowercase wire values (`"hq"`, `"tier"`, `"project"`,
 * `"business"`); missing/absent `scope` defaults to [`BoardScope::Hq`]. An
 * unknown scope string fails to deserialize (surfaced as a 400 via the
 * existing malformed-request `ErrorPayload` path).
 */
export enum BoardScope {
	/** Whole-brain aggregate (`mev::brain::state::TierScope::All`). */
	Hq = "hq",
	/** Single tier's aggregate board (`TierScope::Tier(<tier>)`, default `"core"`). */
	Tier = "tier",
	/**
	 * Single tier resolved per-project (client renders each project's board
	 * from `repos[]`); same underlying `TierScope::Tier(<tier>)`.
	 */
	Project = "project",
	/** Shortcut for `tier=business` (`TierScope::Tier("business")`). */
	Business = "business",
}

/** The three Attention board lanes. */
export interface AttentionLanesDto {
	/** `carryover[]` entries past their per-`kind` threshold, oldest-first. */
	stale_carryover?: AttentionCarryoverDto[];
	/** Non-capture `backlog[]` nodes past `backlog_days`, oldest-first. */
	aging_backlog?: AttentionBacklogDto[];
	/** `backlog[]` nodes with `origin.type == "capture"` past `backlog_days`, oldest-first. */
	orphaned_captures?: AttentionBacklogDto[];
}

/**
 * The resolved `brain.toml` `[attention]` thresholds, mirroring
 * `mev::brain::config::AttentionThresholds`.
 */
export interface AttentionThresholdsDto {
	/** Threshold (days) for `kind == "env"` carryover. */
	env_days: number;
	/** Threshold (days) for `kind == "deferred"` carryover. */
	deferred_days: number;
	/** Threshold (days) for `kind == "known_issue"` carryover. */
	known_issue_days: number;
	/** Threshold (days) for `kind == "constraint"` carryover. */
	constraint_days: number;
	/** Threshold (days) for aging/orphaned `backlog[]` nodes. */
	backlog_days: number;
}

/** JSON response for `GET /api/attention?scope=hq|tier|project|business[&tier=<name>]`. */
export interface AttentionDto {
	/**
	 * The resolved scope this response was projected under. Reuses [`BoardScope`] — the
	 * `/api/attention` query semantics are identical to `/api/board`.
	 */
	scope?: BoardScope;
	/** The resolved tier name, when `scope` is tier-scoped (`None` for `hq`). */
	tier?: string;
	/** `YYYY-MM-DD` the ages were computed against. */
	as_of: string;
	/** The three Attention lanes. */
	lanes: AttentionLanesDto;
	/** The resolved thresholds used to compute every `age_days` / `threshold_days` pair above. */
	thresholds: AttentionThresholdsDto;
}

/**
 * One lane entry (a single now/next/blocked/finished block) in a board response.
 * 
 * Wire format:
 * `{ "id": "BA.11.K", "title": "Cross-brain board read endpoint", "repo": "bastion", "status": "in_progress", "blocked_by": [] }`
 */
export interface BoardBlockDto {
	/** Canonical block ID (e.g. `BA.11.K`). */
	id: string;
	/** Brief human description, looked up from the owning repo's `tracks[].blocks[]`. */
	title: string;
	/** Owning repo slug. */
	repo: string;
	/** Lifecycle status, when known (`"open"`/`"in_progress"`/`"closed"`). */
	status?: string;
	/** What this block is waiting on (populated for `blocked` lane entries). */
	blocked_by?: BlockedBy[];
}

/** The four now/next/blocked/finished lanes for one board (aggregate or per-repo). */
export interface BoardLaneDto {
	/** Blocks currently in progress. */
	now?: BoardBlockDto[];
	/** Blocks queued for next (ordered). */
	next?: BoardBlockDto[];
	/** Blocks waiting on something. */
	blocked?: BoardBlockDto[];
	/** Blocks whose `status == "closed"`. */
	finished?: BoardBlockDto[];
}

/** One repo's lane breakdown within a `scope=project` board response. */
export interface RepoBoardDto {
	/** Repo slug. */
	repo: string;
	/** Tier classification, when known (e.g. `"core"`, `"business"`). */
	tier?: string;
	/** This repo's own four lanes. */
	lanes: BoardLaneDto;
}

/** JSON response for `GET /api/board?scope=hq|tier|project|business[&tier=<name>]`. */
export interface BoardDto {
	/** The resolved scope this response was projected under. */
	scope?: BoardScope;
	/** The resolved tier name, when `scope` is tier-scoped (`None` for `hq`). */
	tier?: string;
	/** Aggregate lanes across all in-scope repos. */
	lanes: BoardLaneDto;
	/** Per-project lane breakdown (populated for `scope=project`; empty otherwise). */
	repos?: RepoBoardDto[];
	/**
	 * Freshness flag: `true` when any in-scope repo's `status.md` cache lags
	 * its `state.json` (derived from `mev::brain::sync::check_sync`).
	 */
	stale: boolean;
}

/**
 * Dispatch mode for `POST /actions/command`.
 * 
 * Serializes/deserializes as the lowercase wire string (`"inject"` / `"spawn"`).
 */
export enum CommandMode {
	/** Send the command into an existing tmux session. */
	Inject = "inject",
	/** Create a new session, launch `claude`, wait for readiness, then send the command. */
	Spawn = "spawn",
}

/**
 * Request body for `POST /actions/command`.
 * 
 * Wire format (inject):
 * ```json
 * { "mode": "inject", "session": "main", "command": "/status" }
 * ```
 * 
 * Wire format (spawn):
 * ```json
 * { "mode": "spawn", "name": "work", "dir": "/repo", "model": "sonnet", "command": "/status" }
 * ```
 * 
 * Field requirements are mode-dependent and enforced by [`CommandRequest::validate`],
 * not by serde: `session` is required for `inject`; `name` is required for `spawn`;
 * `model`, when present, must be one of [`ALLOWED_COMMAND_MODELS`].
 */
export interface CommandRequest {
	/** Dispatch mode: `"inject"` or `"spawn"`. */
	mode: CommandMode;
	/** Target tmux session name. Required when `mode:"inject"`. */
	session?: string;
	/** Name for the new tmux session. Required when `mode:"spawn"`. */
	name?: string;
	/** Optional starting directory for a spawned session. */
	dir?: string;
	/** Optional Claude model for a spawned session; one of [`ALLOWED_COMMAND_MODELS`]. */
	model?: string;
	/** The slash command (or literal text) to send once the target session is ready. */
	command: string;
}

/**
 * Response body for `POST /actions/command`.
 * 
 * Wire format: `{ "session": "work" }`
 */
export interface CommandResponse {
	/** The target tmux session id (existing for inject, newly created for spawn). */
	session: string;
}

/**
 * Payload shape for `WsFrameKind::Error` frames.
 * 
 * Allows the server to surface typed error information over the WS channel.
 */
export interface ErrorPayload {
	/** Short machine-readable error code (e.g. `"C001"`). */
	code: string;
	/** Human-readable error message. */
	message: string;
}

/**
 * Payload for server→client `event` frames (e.g. `needs_input`).
 * 
 * Wire format: `{ "session": "main", "event": "needs_input" }`
 */
export interface EventPayload {
	/** Session that triggered the event. */
	session: string;
	/** Event name; currently only `"needs_input"` is defined. */
	event: string;
}

/**
 * JSON body returned by `GET /health`.
 * 
 * Matches the shape documented in `docs/serve-api.md` v0:
 * ```json
 * { "status": "ok", "service": "bastion" }
 * ```
 */
export interface HealthResponse {
	/** Liveness status; always `"ok"` when the server is healthy. */
	status: string;
	/** Service identifier; always `"bastion"`. */
	service: string;
}

/**
 * Request body for `POST /api/sessions/{name}/key`.
 * 
 * Sends a single named tmux key (e.g. `"Escape"`, `"Up"`, `"C-c"`) without
 * the `-l` flag so tmux resolves the symbolic key name.
 * 
 * Wire format: `{ "key": "Escape" }`
 * 
 * Accepted key names include: `Escape`, `Enter`, `Up`, `Down`, `Left`,
 * `Right`, and modifier combinations such as `C-c`.
 */
export interface KeyBody {
	/** Symbolic tmux key name to send (e.g. `"Escape"`, `"Up"`, `"C-c"`). */
	key: string;
}

/**
 * Request body for `POST /api/sessions` (create a new tmux session).
 * 
 * Wire format: `{ "name": "mysession", "dir": "/optional/start/dir" }`
 */
export interface NewSessionBody {
	/** Name of the new tmux session to create. */
	name: string;
	/** Optional starting directory for the session. */
	dir?: string;
}

/**
 * Token/model usage for an LLM node, projected from `engine_contract::task_context::Usage`.
 * 
 * Wire format:
 * ```json
 * { "input_tokens": 512, "output_tokens": 128, "model": "claude-sonnet-5" }
 * ```
 */
export interface RunUsageDto {
	/** Prompt token count, when reported by the provider. */
	input_tokens?: number;
	/** Completion token count, when reported by the provider. */
	output_tokens?: number;
	/** Model identifier used for this node's LLM call. */
	model: string;
}

/**
 * One node's projected run state — the join of `TaskContext::node_runs[class]`
 * (status/timing/error/input/usage) with `TaskContext::nodes[class]` (output),
 * keyed by the node's class name (BA.11.M).
 * 
 * Wire format:
 * ```json
 * {
 * "node": "DataIngestionNode",
 * "status": "success",
 * "started_at": "2026-07-24T12:00:00Z",
 * "completed_at": "2026-07-24T12:00:01Z",
 * "error": null,
 * "input": null,
 * "output": { "documents_loaded": 3 },
 * "usage": null
 * }
 * ```
 */
export interface NodeTransitionDto {
	/**
	 * Node identity — the Python class name (contract §1), used as the map key
	 * in both `TaskContext::nodes` and `TaskContext::node_runs`.
	 */
	node: string;
	/** Lifecycle status as the lowercase wire string: `pending`/`running`/`success`/`failed`. */
	status: string;
	/** ISO-8601 UTC timestamp set on entry, `null` while pending. */
	started_at?: string;
	/** ISO-8601 UTC timestamp set on success or failure, `null` before completion. */
	completed_at?: string;
	/** Error message, present only for a `failed` node. */
	error?: string;
	/** The node's recorded input, present only for a `failed` node. */
	input?: any;
	/** The node's output value from `TaskContext::nodes`, `null` when not yet produced. */
	output?: any;
	/** Token/model usage, present only for LLM nodes. */
	usage?: RunUsageDto;
}

/**
 * JSON response for `GET /api/sessions/{name}/pane`.
 * 
 * Wire format:
 * ```json
 * { "session_name": "main", "lines": ["line1", "line2"] }
 * ```
 */
export interface PaneDto {
	/** tmux session name this pane belongs to. */
	session_name: string;
	/** Lines of captured pane output (trailing blank padding stripped). */
	lines: string[];
}

/**
 * Payload for server→client `pane` frames (pane diff push).
 * 
 * Wire format: `{ "session": "main", "seq": 42, "lines": ["line1", "line2"] }`
 */
export interface PanePayload {
	/** tmux session name whose pane was captured. */
	session: string;
	/** Monotonically increasing sequence number; bumped on every diff push. */
	seq: number;
	/** Non-blank trailing lines from the captured pane output. */
	lines: string[];
}

/**
 * JSON response for `GET /repos/{name}/status`.
 * 
 * Mirrors [`crate::serve::status::repo::RepoStatus`] field-for-field — kept
 * as an independent DTO (per this module's doc comment) rather than reusing
 * the domain type directly.
 */
export interface RepoStatusDto {
	/** Workspace registry name. */
	name: string;
	/** Frontmatter `now:` scalar. */
	now: string;
	/** Frontmatter `next:` scalar. */
	next: string;
	/** Frontmatter `blocked:` scalar. */
	blocked: string;
	/** Whether `planning/handoff.md` exists. */
	has_handoff: boolean;
	/** Body `## Momentum` → `now` queue line text. */
	momentum_now: string;
	/** Body `## Momentum` → `next` queue line text. */
	momentum_next: string;
	/** Body `## Momentum` → `blocked` queue line text. */
	momentum_blocked: string;
	/** Body `## Momentum` → `improve` queue line text. */
	momentum_improve: string;
	/** Body `## Momentum` → `recurring` queue line text. */
	momentum_recurring: string;
}

/**
 * JSON response element for `GET /repos` (one per workspace registry entry).
 * 
 * Wire format: `{ "name": "bastion", "now": "BA.11.D in progress", "has_handoff": false }`
 */
export interface RepoSummaryDto {
	/** Workspace registry name. */
	name: string;
	/** Frontmatter `now:` scalar from the repo's `planning/status.md`. */
	now: string;
	/** Whether `planning/handoff.md` exists for this workspace. */
	has_handoff: boolean;
}

/**
 * JSON response for `GET /api/runs/{id}` — the projected `LiveStateStore` snapshot
 * for one run (BA.11.M).
 * 
 * Wire format:
 * ```json
 * {
 * "run_id": "b6a1...",
 * "event": { "ticket_id": "T-1" },
 * "metadata": { "workflow": "sdlc-flow" },
 * "nodes": [ { "node": "DataIngestionNode", "status": "success", ... } ]
 * }
 * ```
 */
export interface RunStateDto {
	/** The run's UUID as a string. */
	run_id: string;
	/** The triggering event payload, carried through from `TaskContext::event`. */
	event: any;
	/** Workflow-level metadata, carried through from `TaskContext::metadata`. */
	metadata: any;
	/** Per-node projected states, one entry per class name in `TaskContext::node_runs`. */
	nodes: NodeTransitionDto[];
}

/**
 * Request body for `POST /api/sessions/{name}/send`.
 * 
 * Sends a literal string of keystrokes to the session followed by `Enter`.
 * Wire format: `{ "keys": "cargo test" }`
 */
export interface SendBody {
	/** Literal text to send to the session (forwarded with `-l`). */
	keys: string;
}

/**
 * Payload for client→server `send_key` frames (single named tmux key).
 * 
 * Wire format: `{ "session": "main", "key": "Escape" }`
 */
export interface SendKeyPayload {
	/** Target tmux session name. */
	session: string;
	/** Symbolic tmux key name (e.g. `"Escape"`, `"Up"`, `"C-c"`). */
	key: string;
}

/**
 * Payload for client→server `send` frames (literal keystrokes + Enter).
 * 
 * Wire format: `{ "session": "main", "keys": "cargo test" }`
 */
export interface SendPayload {
	/** Target tmux session name. */
	session: string;
	/** Literal text to send (forwarded with `-l`), followed by Enter. */
	keys: string;
}

/**
 * JSON response for a single tmux session (one element of `GET /api/sessions`).
 * 
 * Wire format:
 * ```json
 * { "name": "main", "state": "running", "last_line": "$ cargo test" }
 * ```
 */
export interface SessionDto {
	/** tmux session name. */
	name: string;
	/** Session state as a string: `"running"` or `"idle"`. */
	state: string;
	/** Last non-blank line from the session's pane, or empty string when unavailable. */
	last_line: string;
}

/**
 * Payload for server→client `sessions` frames (session list snapshot).
 * 
 * Wire format: `{ "sessions": [ … ] }`
 */
export interface SessionsPayload {
	/** Current snapshot of all tmux sessions. */
	sessions: SessionDto[];
}

/**
 * Payload for client→server `subscribe` / `unsubscribe` frames.
 * 
 * Wire format: `{ "topic": "sessions" }` or `{ "topic": "pane:work" }`
 */
export interface SubscribePayload {
	/** Topic string: `"sessions"` or `"pane:<name>"`. */
	topic: string;
}

/**
 * Payload for the server→client `event{workflow_done}` WS push.
 * 
 * Sent inside an [`EventPayload`]-shaped frame: the `event` field is fixed
 * to `"workflow_done"` and the extra repo/spec_slug/status fields are
 * flattened into the same JSON object by the caller (Task 4 WS wiring).
 * 
 * Wire format: `{ "repo": "bastion", "spec_slug": "phase11-blockD", "status": "done" }`
 */
export interface WorkflowDonePayload {
	/** Workspace registry name the workflow belongs to. */
	repo: string;
	/** `sdlc-flow-state.json` spec slug. */
	spec_slug: string;
	/** The terminal status that triggered the event (`"done"` or `"blocked"`). */
	status: string;
}

/**
 * JSON response element for `GET /repos/{name}/workflows`.
 * 
 * Serializable projection of [`crate::serve::status::flow::FlowState`].
 */
export interface WorkflowStateDto {
	spec_slug: string;
	branch: string;
	/** Raw status string, e.g. `"running"`, `"done"`, `"blocked"`. */
	status: string;
	current_task: number;
	started_at: string;
	updated_at: string;
}

/**
 * Discriminant for [`WsFrame::kind`].
 * 
 * v0 defined `Echo` and `Error`.  v0.2 adds client→server kinds (`Subscribe`,
 * `Unsubscribe`, `Send`, `SendKey`) and server→client kinds (`Sessions`, `Pane`,
 * `Event`).
 */
export enum WsFrameKind {
	/** Echo — the `/ws` actor reflects the received frame back unchanged (v0). */
	Echo = "echo",
	/** Error — server-side error notification pushed to the client. */
	Error = "error",
	/** Subscribe to a topic (`sessions` or `pane:<name>`). */
	Subscribe = "subscribe",
	/** Unsubscribe from a topic. */
	Unsubscribe = "unsubscribe",
	/** Send literal keystrokes to a tmux session (followed by Enter). */
	Send = "send",
	/** Send a single named tmux key to a session (e.g. `"Escape"`, `"C-c"`). */
	SendKey = "send_key",
	/** Session list snapshot pushed to `sessions` subscribers. */
	Sessions = "sessions",
	/** Pane diff pushed to `pane:<name>` subscribers. */
	Pane = "pane",
	/** Async event pushed to all subscribed connections (e.g. `needs_input`). */
	Event = "event",
}

/**
 * Tagged WebSocket frame envelope.
 * 
 * Every WS message sent or received by `bastion serve` is wrapped in this
 * envelope so the Flutter client can dispatch on `kind` before parsing
 * `payload`.  This is the v0 skeleton; later blocks add concrete `kind`
 * variants and payload types.
 * 
 * Wire format (JSON):
 * ```json
 * { "kind": "echo", "payload": <any JSON value> }
 * ```
 */
export interface WsFrame {
	/** Frame type discriminant.  The Flutter client switches on this field. */
	kind: WsFrameKind;
	/** Arbitrary JSON payload.  Shape is defined per-kind in the serve-api contract. */
	payload: any;
}

